version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bmx_postgres
    environment:
      POSTGRES_DB: bmx_racing
      POSTGRES_USER: bmx_user
      POSTGRES_PASSWORD: bmx_password_2024
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
